# Generated by Django 4.2.5 on 2023-10-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
            ],
        ),
    ]
